name: Generate terraform docs
on:
  workflow_dispatch:
    inputs:
      deployment:
        description: 'deployment'
        required: true
        default: ''
        
env: 
  ROOT_PATH: '${{ github.workspace }}/src/deployment${{ github.event.inputs.deployment }}/terraform'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
         
    - name: Generate TF Docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
          find-dir: ${{ env.ROOT_PATH }}
          output-file: README.md
          output-method: inject
          git-push: true
           
            
