name: AzureRM Backend Configuration

on:
  push:
    branches:
      - main


env: 

  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  STORAGE_ACCOUNT_NAME: ${{secrets.AZURE_STORAGE_NAME}}
  STORAGE_CONTAINER_NAME: ${{secrets.AZURE_CONTAINER_NAME}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  STATE_FILE_NAME: deployment${{ github.event.inputs.deployment }}.tfstate
  STORAGE_ACCOUNT_ACCESS_KEY: ${{secrets.STORAGE_ACCOUNT_ACCESS_KEY}}
  
  
jobs:
  backend-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1

      - name: Authenticate with Azure
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}


      - name: Configure AzureRM Backend
        run: |
          export ARM_ACCESS_KEY="${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.ARM_SUBSCRIPTION_ID }}"
          export ARM_RESOURCE_GROUP_NAME="same0099"
          export ARM_STORAGE_ACCOUNT_NAME="${{ secrets.ARM_SUBSCRIPTION_ID }}"
          export ARM_CONTAINER_NAME=${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
          terraform init -backend-config="resource_group_name=${ARM_RESOURCE_GROUP_NAME}" -backend-config="storage_account_name=${ARM_STORAGE_ACCOUNT_NAME}" -backend-config="container_name=${ARM_CONTAINER_NAME}"
